services:
  - type: web
    name: secure-chatroom-v2
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: FORCE_HTTPS
        value: false 